# Generated by Django 3.1.4 on 2021-01-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_before_img', models.ImageField(default='before.jpg', upload_to='', verbose_name='Patient Case Before Image')),
                ('case_after_img', models.ImageField(default='after.jpg', upload_to='', verbose_name='Patient Case After Image')),
                ('patient_english_name', models.CharField(max_length=350, verbose_name="Case's English Name")),
                ('patient_arabic_name', models.CharField(max_length=350, verbose_name="Case's Arabic Name")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
            },
        ),
    ]
