# Generated by Django 3.1.4 on 2020-12-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients_Cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='case_img',
        ),
        migrations.AddField(
            model_name='case',
            name='case_after_img',
            field=models.ImageField(default='after.jpg', upload_to='', verbose_name='Patient Case After Image'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_before_img',
            field=models.ImageField(default='before.jpg', upload_to='', verbose_name='Patient Case Before Image'),
        ),
    ]
