# Generated by Django 3.1.4 on 2021-01-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_english_name', models.CharField(max_length=350, verbose_name='Item Name In English')),
                ('item_arabic_name', models.CharField(max_length=350, verbose_name='Item Name In Arabic')),
                ('item_price', models.FloatField(verbose_name='Item Price')),
            ],
            options={
                'verbose_name': 'Item Offer',
                'verbose_name_plural': 'Item Offers',
            },
        ),
    ]
