# Generated by Django 3.1.4 on 2020-12-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_img', models.ImageField(upload_to='')),
                ('branch_name', models.CharField(max_length=350, verbose_name='Branch Name')),
                ('branch_address', models.CharField(max_length=500, verbose_name='Branch Address')),
                ('branch_phone', models.CharField(max_length=500, verbose_name='Branch Phone')),
                ('branch_manager', models.CharField(max_length=50, verbose_name='Branch Manager')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
    ]
