# Generated by Django 3.1.4 on 2021-01-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350, verbose_name='First Name')),
                ('age', models.CharField(max_length=350, verbose_name='Age')),
                ('date_of_birth', models.CharField(max_length=350, verbose_name='Date Of Birth')),
                ('phone_number', models.CharField(max_length=350, verbose_name='Phone Number')),
                ('email', models.CharField(max_length=350, verbose_name='Email Address')),
                ('address', models.CharField(max_length=350, verbose_name='Address')),
                ('branch', models.CharField(max_length=350, verbose_name='Choosed Branch')),
                ('boooked_at', models.DateTimeField(auto_now_add=True, verbose_name='Booked At')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
