# Generated by Django 3.1.4 on 2021-01-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='case',
            field=models.CharField(default='patient case', max_length=350, verbose_name="Patient's Case"),
            preserve_default=False,
        ),
    ]
