# Generated by Django 3.1.4 on 2021-01-18 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_booking_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='address',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='case',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date_of_birth',
        ),
    ]
