# Generated by Django 3.1.4 on 2021-01-20 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_auto_20210118_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
    ]
