# Generated by Django 3.1.4 on 2021-01-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_english_name', models.CharField(max_length=350, verbose_name="Item's English Name")),
                ('item_arabic_name', models.CharField(max_length=350, verbose_name="Item's Arabic Name")),
                ('item_price', models.FloatField(verbose_name='Item Price')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pricing',
                'verbose_name_plural': 'Pricings',
            },
        ),
    ]
