# Generated by Django 3.1.4 on 2021-01-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_photo', models.ImageField(upload_to='')),
                ('doctor_english_name', models.CharField(max_length=500, verbose_name="Doctor's English Name")),
                ('doctor_arabic_name', models.CharField(max_length=500, verbose_name="Doctor's Arabic Name")),
                ('speciality_in_english', models.CharField(max_length=750, verbose_name="Doctor's Speciality in english")),
                ('speciality_in_arabic', models.CharField(max_length=750, verbose_name="Doctor's Speciality in arabic")),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
    ]
