# Generated by Django 3.1.4 on 2020-12-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_photo', models.ImageField(upload_to='')),
                ('doctor_name', models.CharField(max_length=500, verbose_name="Doctor's Name")),
                ('speciality', models.CharField(max_length=750, verbose_name="Doctor's Speciality")),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
    ]
